//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitterEnhancedViewer.LangString {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NitterEnhancedViewer.LangString.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is immediately to open setting ?.
        /// </summary>
        public static string M_AskOpenSetting {
            get {
                return ResourceManager.GetString("M_AskOpenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Didn&apos;t set Xaccount to setting.
        /// </summary>
        public static string M_DidntXaccountSetting {
            get {
                return ResourceManager.GetString("M_DidntXaccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t complete XLogin on setting.
        /// </summary>
        public static string M_NotXLoginOnSetting {
            get {
                return ResourceManager.GetString("M_NotXLoginOnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string M_OK {
            get {
                return ResourceManager.GetString("M_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged in to X.
        /// </summary>
        public static string M_XAlreadyloggin {
            get {
                return ResourceManager.GetString("M_XAlreadyloggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string S_Account {
            get {
                return ResourceManager.GetString("S_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountName.
        /// </summary>
        public static string S_AccountName {
            get {
                return ResourceManager.GetString("S_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountPassword.
        /// </summary>
        public static string S_AccountPassword {
            get {
                return ResourceManager.GetString("S_AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string S_Application {
            get {
                return ResourceManager.GetString("S_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DockColor.
        /// </summary>
        public static string S_DockColor {
            get {
                return ResourceManager.GetString("S_DockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string S_FavoriteList {
            get {
                return ResourceManager.GetString("S_FavoriteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string S_General {
            get {
                return ResourceManager.GetString("S_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string S_Language {
            get {
                return ResourceManager.GetString("S_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string S_Login {
            get {
                return ResourceManager.GetString("S_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login X.
        /// </summary>
        public static string S_LoginX {
            get {
                return ResourceManager.GetString("S_LoginX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryTab.
        /// </summary>
        public static string S_MemoryTab {
            get {
                return ResourceManager.GetString("S_MemoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string S_Message {
            get {
                return ResourceManager.GetString("S_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string S_Profile {
            get {
                return ResourceManager.GetString("S_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string S_SavedIconFalse {
            get {
                return ResourceManager.GetString("S_SavedIconFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string S_SavedIconTrue {
            get {
                return ResourceManager.GetString("S_SavedIconTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string S_Settings {
            get {
                return ResourceManager.GetString("S_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartMinimized.
        /// </summary>
        public static string S_StartMinimized {
            get {
                return ResourceManager.GetString("S_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string S_Theme {
            get {
                return ResourceManager.GetString("S_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet.
        /// </summary>
        public static string S_Tweet {
            get {
                return ResourceManager.GetString("S_Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string S_Url {
            get {
                return ResourceManager.GetString("S_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string S_View {
            get {
                return ResourceManager.GetString("S_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This open source application does not collect any Xaccount information. If you are still uncomfortable entering your user name and password, we recommend that you do not use this application..
        /// </summary>
        public static string ST_WarningUseXAccount {
            get {
                return ResourceManager.GetString("ST_WarningUseXAccount", resourceCulture);
            }
        }
    }
}
