//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitterEnhancedViewer.LangString {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NitterEnhancedViewer.LangString.Language.ja-JP", typeof(Language_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今すぐセッティングを開きますか？.
        /// </summary>
        public static string M_AskOpenSetting {
            get {
                return ResourceManager.GetString("M_AskOpenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xaccountが設定されていません.
        /// </summary>
        public static string M_DidntXaccountSetting {
            get {
                return ResourceManager.GetString("M_DidntXaccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定ウィンドウでのXのログインが完了していません.
        /// </summary>
        public static string M_NotXLoginOnSetting {
            get {
                return ResourceManager.GetString("M_NotXLoginOnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認.
        /// </summary>
        public static string M_OK {
            get {
                return ResourceManager.GetString("M_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xにログイン済みです.
        /// </summary>
        public static string M_XAlreadyloggin {
            get {
                return ResourceManager.GetString("M_XAlreadyloggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウント.
        /// </summary>
        public static string S_Account {
            get {
                return ResourceManager.GetString("S_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウント名.
        /// </summary>
        public static string S_AccountName {
            get {
                return ResourceManager.GetString("S_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウントパスワード.
        /// </summary>
        public static string S_AccountPassword {
            get {
                return ResourceManager.GetString("S_AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーション.
        /// </summary>
        public static string S_Application {
            get {
                return ResourceManager.GetString("S_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドックカラー.
        /// </summary>
        public static string S_DockColor {
            get {
                return ResourceManager.GetString("S_DockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いいね一覧.
        /// </summary>
        public static string S_FavoriteList {
            get {
                return ResourceManager.GetString("S_FavoriteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般.
        /// </summary>
        public static string S_General {
            get {
                return ResourceManager.GetString("S_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        public static string S_Language {
            get {
                return ResourceManager.GetString("S_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string S_Login {
            get {
                return ResourceManager.GetString("S_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xにログインする.
        /// </summary>
        public static string S_LoginX {
            get {
                return ResourceManager.GetString("S_LoginX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タブを記憶する.
        /// </summary>
        public static string S_MemoryTab {
            get {
                return ResourceManager.GetString("S_MemoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メッセージ.
        /// </summary>
        public static string S_Message {
            get {
                return ResourceManager.GetString("S_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロフィール.
        /// </summary>
        public static string S_Profile {
            get {
                return ResourceManager.GetString("S_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブする.
        /// </summary>
        public static string S_SavedIconFalse {
            get {
                return ResourceManager.GetString("S_SavedIconFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存済み.
        /// </summary>
        public static string S_SavedIconTrue {
            get {
                return ResourceManager.GetString("S_SavedIconTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string S_Settings {
            get {
                return ResourceManager.GetString("S_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動時最小化.
        /// </summary>
        public static string S_StartMinimized {
            get {
                return ResourceManager.GetString("S_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーマ.
        /// </summary>
        public static string S_Theme {
            get {
                return ResourceManager.GetString("S_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツイートする.
        /// </summary>
        public static string S_Tweet {
            get {
                return ResourceManager.GetString("S_Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string S_Url {
            get {
                return ResourceManager.GetString("S_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外見.
        /// </summary>
        public static string S_View {
            get {
                return ResourceManager.GetString("S_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このオープンソースアプリケーションはXaccountの情報収集を一切行いません。それでもユーザー名とパスワードを入力するのに抵抗が有る方はご利用しないことをおすすめします。.
        /// </summary>
        public static string ST_WarningUseXAccount {
            get {
                return ResourceManager.GetString("ST_WarningUseXAccount", resourceCulture);
            }
        }
    }
}
